"""add refresh token security

Revision ID: 69a8fef09b21
Revises: e3d7a981449d
Create Date: 2026-04-18 14:48:09.519619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69a8fef09b21'
down_revision: Union[str, Sequence[str], None] = 'e3d7a981449d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('device_fingerprint', sa.String(length=255), nullable=True))
    op.add_column('refresh_tokens', sa.Column('ip_address', sa.String(length=45), nullable=True))
    op.add_column('refresh_tokens', sa.Column('rotated_from', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'refresh_tokens', 'refresh_tokens', ['rotated_from'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_column('refresh_tokens', 'rotated_from')
    op.drop_column('refresh_tokens', 'ip_address')
    op.drop_column('refresh_tokens', 'device_fingerprint')
    # ### end Alembic commands ###
