"""initial

Revision ID: e3d7a981449d
Revises: 
Create Date: 2026-04-18 12:37:58.983270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e3d7a981449d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_expirations')
    op.create_index(op.f('ix_cart_items_id'), 'cart_items', ['id'], unique=False)
    op.drop_constraint(op.f('cart_items_ibfk_1'), 'cart_items', type_='foreignkey')
    op.drop_constraint(op.f('cart_items_ibfk_2'), 'cart_items', type_='foreignkey')
    op.create_foreign_key(None, 'cart_items', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart_items', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_email_otps_email'), 'email_otps', ['email'], unique=False)
    op.create_index(op.f('ix_email_otps_id'), 'email_otps', ['id'], unique=False)
    op.alter_column('order_items', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_order_items_id'), 'order_items', ['id'], unique=False)
    op.drop_constraint(op.f('order_items_ibfk_2'), 'order_items', type_='foreignkey')
    op.drop_constraint(op.f('order_items_ibfk_1'), 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'products', ['product_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.add_column('orders', sa.Column('idempotency_key', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.create_unique_constraint(None, 'orders', ['idempotency_key'])
    op.drop_constraint(op.f('orders_ibfk_1'), 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_payment_orders_id'), 'payment_orders', ['id'], unique=False)
    op.drop_constraint(op.f('payment_orders_ibfk_1'), 'payment_orders', type_='foreignkey')
    op.create_foreign_key(None, 'payment_orders', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('product_images', 'image_uuid',
               existing_type=mysql.CHAR(length=36),
               type_=sa.String(length=36),
               existing_nullable=False)
    op.create_index(op.f('ix_product_images_id'), 'product_images', ['id'], unique=False)
    op.drop_constraint(op.f('product_images_ibfk_1'), 'product_images', type_='foreignkey')
    op.create_foreign_key(None, 'product_images', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_products_id'), 'products', ['id'], unique=False)
    op.create_index(op.f('ix_profile_avatars_id'), 'profile_avatars', ['id'], unique=False)
    op.alter_column('refresh_tokens', 'token',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_unique_constraint(None, 'refresh_tokens', ['token'])
    op.create_foreign_key(None, 'refresh_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    op.drop_constraint(op.f('user_profiles_ibfk_1'), 'user_profiles', type_='foreignkey')
    op.create_foreign_key(None, 'user_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'auth_provider',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'local'"))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', mysql.VARCHAR(length=255), nullable=True))
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'auth_provider',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'local'"))
    op.drop_constraint(None, 'user_profiles', type_='foreignkey')
    op.create_foreign_key(op.f('user_profiles_ibfk_1'), 'user_profiles', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.alter_column('refresh_tokens', 'token',
               existing_type=sa.String(length=500),
               type_=mysql.TEXT(),
               existing_nullable=False)
    op.drop_index(op.f('ix_profile_avatars_id'), table_name='profile_avatars')
    op.drop_index(op.f('ix_products_id'), table_name='products')
    op.drop_constraint(None, 'product_images', type_='foreignkey')
    op.create_foreign_key(op.f('product_images_ibfk_1'), 'product_images', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_product_images_id'), table_name='product_images')
    op.alter_column('product_images', 'image_uuid',
               existing_type=sa.String(length=36),
               type_=mysql.CHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(None, 'payment_orders', type_='foreignkey')
    op.create_foreign_key(op.f('payment_orders_ibfk_1'), 'payment_orders', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_payment_orders_id'), table_name='payment_orders')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key(op.f('orders_ibfk_1'), 'orders', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'orders', type_='unique')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_column('orders', 'idempotency_key')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key(op.f('order_items_ibfk_1'), 'order_items', 'orders', ['order_id'], ['id'])
    op.create_foreign_key(op.f('order_items_ibfk_2'), 'order_items', 'products', ['product_id'], ['id'])
    op.drop_index(op.f('ix_order_items_id'), table_name='order_items')
    op.alter_column('order_items', 'product_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_email_otps_id'), table_name='email_otps')
    op.drop_index(op.f('ix_email_otps_email'), table_name='email_otps')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.drop_constraint(None, 'cart_items', type_='foreignkey')
    op.create_foreign_key(op.f('cart_items_ibfk_2'), 'cart_items', 'products', ['product_id'], ['id'])
    op.create_foreign_key(op.f('cart_items_ibfk_1'), 'cart_items', 'users', ['user_id'], ['id'])
    op.drop_index(op.f('ix_cart_items_id'), table_name='cart_items')
    op.create_table('token_expirations',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('access_token_expires_in', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('refresh_token_expires_in', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
